// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Prueba.Entities.Entities;

public partial class DetalleOrden
{
    public long DetalleOrdenId { get; set; }

    public long OrdenId { get; set; }

    public long ProductoId { get; set; }

    public int Cantidad { get; set; }

    public decimal Impuesto { get; set; }

    public decimal Subtotal { get; set; }

    public decimal Total { get; set; }

    public virtual Orden Orden { get; set; }

    public virtual Producto Producto { get; set; }
}